# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
    command = "npm run build"
    publish="build/"
    base = "client/"